name: Makefile CI

on:
  push:
    branches:
      - master
      - release-*
      - development-*
      
  pull_request:
    branches:
      - master
      - release-*
      - development-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies.
      run: |
        sudo apt-get update
        sudo apt-get install valgrind
        
    - name: Build the project.
      run: make

    - name: Run tests and checks.
      run: make check
