name: Makefile CI

on:
  push:
    branches:
      - master
      - development
      
  pull_request:
    branches:
      - master
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the project.
      run: make

    - name: Run tests and checks.
      run: make check
